# Generated by Django 5.0.6 on 2026-04-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='issues/')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.CharField(blank=True, max_length=500)),
                ('issue_type', models.CharField(choices=[('STREET_LIGHT', 'Street Light'), ('GARBAGE', 'Garbage'), ('WATER', 'Water'), ('ROAD', 'Road')], max_length=20)),
                ('location_type', models.CharField(choices=[('URBAN', 'Urban'), ('SEMI_URBAN', 'Semi Urban'), ('RURAL', 'Rural')], default='URBAN', max_length=20)),
                ('priority_score', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('REPORTED', 'Reported'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('ESCALATED', 'Escalated')], default='REPORTED', max_length=20)),
                ('current_level', models.IntegerField(default=1)),
                ('likes_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'issues',
                'ordering': ['-priority_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'likes',
            },
        ),
    ]
